name: "zig get build test (TODO)"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget libgtk-3-dev
      - name: Setup zig
        run: |
          wget https://ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.1622+fc48467a9.tar.xz
          mkdir zig
          tar -xf zig-linux-x86_64-0.11.0-dev.1622+fc48467a9.tar.xz -C zig --strip-components=1
          echo "::add-path::$(pwd)/zig"
